### ISSUE TITLE
The package is still broken because build was not rebuilt

### ISSUE THREAD

**Issue by GrosSacASac** [Polarisation/iso-639-1-plus#2]
https://npmfs.com/compare/iso-639-1-plus/3.0.1/3.0.2/

As you can see here the fix did not go into build/

but Node.js imports from iso-639-1-plus\build\index.js

To avoid this situation in the future I recommend:

- Remove build/ artifact from git (to avoid polluting the commits with double changes)
- Add a npm publish hook to build just before publish automatically (to avoid forgetting to build)
- specify what exact files go to npm publish (src and build) (eslintrc and .vscode should not be in npm)

**Comment by GrosSacASac** [comment]
Made a PR: https://github.com/Polarisation/iso-639-1-plus/pull/3

**Comment by Polarisation** [comment]
Thank you, published a new version, let me know if any issues.
